### PR TITLE
Update to 5.6.1.0, improve packaging

### PR DESCRIPTION
**Pull request by KF-Art**
Overall improvements for this template, mirrored from [cereus-pkgs](https://codeberg.org/cereus-linux/cereus-pkgs/src/branch/master/srcpkgs/megasync) for Void Linux users convenience (although cereus-pkgs should be completely compatible with Void Linux) as per request at #2.

- Package was updated to its latest version.
- Now it uses the Linux release instead of the Win one.
- A note about maintainership was added.
- pdfium.patch was removed since a CMake flags now takes care of that.
- Some patches from AUR were added.
- `update` file was updated.
- pkgname was case-lowered. You might need to remove the old version before installing this. You could add a transitional dummy package if you'd want. I didn't add it because you have to build and install it manually anyways.
- `freeimage` dependency is back thanks to `-DCMAKE_MODULE_PATH` configure argument.
- Added myself as maintainer. Leaving John as maintainer felt somehow wrong for me.
- A trailing whitespace in license was removed.
- Now distfiles are downloaded and managed by `xbps-src`. The SDK commit version is based on what is defined in the corresponding tag, in this case `ecc873026fcc0355f6d490b8529c9f22d5a4fd8c`.
- `-DCMAKE_INSTALL_PREFIX:PATH` configure argument is defined to `'/'`, since otherwise it installs it to the wrong path.

I'll do my best to keep this updated but can't guarantee it will be on par with its `cereus-pkgs` counterpart.

### CODE REVIEW

**Comment by ibhagwan** [comment]
Than you so much @KF-Art!

Not sure how much this matters as it seems to work  regardless but I added a missing end quote in `changelog`.

https://github.com/ibhagwan/megasync-template/commit/d28b6486c7ee6f59de49e698f65cb982c4f95217

**Comment by ibhagwan** [comment]
@KF-Art, on another note, what are the changes of this being included in the upstream?

Wouldn't that be the best for everyone? instead of having to search for this and getting to this esoteric repo?

**Comment by KF-Art** [comment]
> Than you so much @KF-Art!
> 
> Not sure how much this matters as it seems to work regardless but I added a missing end quote in `changelog`.
> 
> [d28b648](https://github.com/ibhagwan/megasync-template/commit/d28b6486c7ee6f59de49e698f65cb982c4f95217)

Oh, forgot to close it, haha. Thanks for that.

**Comment by KF-Art** [comment]
> @KF-Art, on another note, what are the changes of this being included in the upstream?
> 
> Wouldn't that be the best for everyone? instead of having to search for this and getting to this esoteric repo?

Do you mean this should be on `void-packages`?
Well, to be honest I don't know why it was removed from it before. 

In general for anything we package in Cereus, we don't ask Void or make a PR to them because our intention is to take care of them ourselves, so I never tried personally to request them to merge something like this. I might consider trying it out, though.

**Comment by ibhagwan** [comment]
> Do you mean this should be on void-packages?
> Well, to be honest I don't know why it was removed from it before.

Correct, I had no idea if was ever there.

**Pull request merged**
